version: '3.8'

services:
  db:
    image: postgres:alpine
    env_file: /apps/backend/api/.env 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}